### ISSUE TITLE
"Run the examples" instructions won't work on Windows

### ISSUE THREAD

**Issue by bookercodes** [pusher-community/gs-pusher-node#2]
The [_Run the examples_](https://github.com/pusher-community/gs-pusher-node#run-the-examples) instructions assume that the user is using Bash or a similar shell:

```
# Bash command (won't work on Windows)
PUSHER_APP_ID=YOUR_APP_ID PUSHER_APP_KEY=YOUR_APP_KEY PUSHER_APP_SECRET=YOUR_APP_SECRET node server.js
```

Windows users will likely want to use the Windows command shell (cmd.exe) or Powershell:

```
# Windows command shell command
set PUSHER_APP_ID=YOUR_APP_ID&& set PUSHER_APP_KEY=YOUR_APP_KEY&& set PUSHER_APP_SECRET=YOUR_APP_SECRET&& node server.js
```

Would you be open to a pull request that adds Windows command shell and/or Powershell commands to the _Run the examples_ section? I'm sure Windows users will find it convenient :+1: 

Thanks

cc @jackfranklin

**Comment by jackfranklin** [comment]
@alexbooker would love a PR - that would be really appreciated :)

**Comment by bookercodes** [comment]
Sure. Should I add cmd.exe or cmd.exd _and_ Powershell instructions?

Would you like me to make a similar pull request for [gs-pusher-rails](https://github.com/pusher-community/gs-pusher-rails)?

**Comment by jackfranklin** [comment]
That would be amazing - and whatever instructions you think is best really :)
